### ISSUE TITLE
Option to remove modified flag from buffer/tab name?

### ISSUE THREAD

**Issue by kosayoda** [rbong/vim-crystalline#11]
Is there a way to hide/remove the modified flag from buffer or tab names?
```
TABS | FileOne.vim[+] | FileTwo.vim[+]
```
Thank you in advance, and let me know if you need further information.

**Comment by rbong** [comment]
In your .vimrc, put `let g:crystalline_tab_mod = ''`. This changes `'[+]'` to `''`.

I just changed how it works for this issue because I wasn't happy with it so you'll have to update to use this option.

For anyone who set this option using the old option please see https://github.com/rbong/vim-crystalline/commit/4634c5fd25e4d521a3678af4fc236d1d970ecacb

Please feel free to reopen if there are any problems, and let me know if you have any more questions.
