### ISSUE TITLE
Integrate vim-devicons

### ISSUE THREAD

**Issue by kablondino** [rbong/vim-crystalline#15]
One of the features that I really liked about lightline is the integration with devicons from Nerd Fonts. Specifically, I want to put them in my tabline. Are there any plans on doing something like this?

I also realize this could be my lack of understanding on how to modify the tabline. A more in-depth example on this may also help.

**Comment by kablondino** [comment]
I also realize this could be my lack of understanding on how to modify the tabline. A more in-depth example on this may also help.

**Comment by rbong** [comment]
Luckily any plugin that provides a function for the statusline works in crystalline. Since crystalline is just a few helpers for the builtin statusline system, and statusline elements just return strings, you just append the output of the function to your statusline or tabline.

[Here is the documentation on integration with lightline](https://github.com/ryanoasis/vim-devicons/wiki/usage#lightline-setup). It uses function output to replace elements in the statusline, so it is already compatible.

Here is an adapted version of the lightline example for crystalline. Since the original example appears to offer drop-in replacements for `&filetype` and `&fileformat`, just replace the `&filetype` and `&fileformat` (or `&ft` and `&ff` for short) elements in your statusline or tabline, or just add these elements where you want them if they're not there. Note that I have not tested this!

```vim
" these next two functions are copied straight from the lightline example for devicons

function! MyFiletype()
  return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype . ' ' . WebDevIconsGetFileTypeSymbol() : 'no ft') : ''
endfunction

function! MyFileformat()
  return winwidth(0) > 70 ? (&fileformat . ' ' . WebDevIconsGetFileFormatSymbol()) : ''
endfunction

" the crystalline example starts here

" example of how to put it in your statusline

function! StatusLine()
  " the uncommented line replaces the commented line
  " return '%{&ft} %{&ff}'
  return '%{MyFiletype()} %{MyFileformat}'
endfunction

let g:crystalline_statusline_fn = 'StatusLine'

" example of how to put it in your tabline

function! TabLine()
  " the uncommented line replaces the commented line
  " let l:right = &ft . ' ' . &ff
  let l:right = MyFiletype() . ' ' . MyFileformat()
  " arguments to this function are as follows: tabline elements used, width of the rest of the tabline, show mode
  return crystalline#bufferline(2, strdisplaywidth(l:right), 1) . '%=%#CrystallineTab# ' . l:right
endfunction

let g:crystalline_tabline_fn = 'TabLine'
```

Thank you for the question, let me know if there are any problems or more questions. I'll wait to close this until it's working since I have not had a chance to test this.

**Comment by kablondino** [comment]
In my lightline configuration, I did just that. This implementation that you posted works. But perhaps I should clarify a bit more: I would like to modify the actual tabs of the buffers to show the icons, i.e. place the icons within the tabs themselves.

Calling the `crystalline#bufferline(...)` function prints at the top left the `BUFFERS` plus the tabs. I would like to modify this part of the tabline to somehow include the icons.

**Comment by rbong** [comment]
Oh, no, it's not possible yet to modify the actual buffer label. However, reviewing the code, it should be possible to implement, although the interface will be a little clunky. I'll have a go at it later and test it.

**Comment by rbong** [comment]
The bufferline now supports customizing the tab label, although I still have to document and test it with devicons. However the base functionality still works the same so I saw no reason not to push it up. You can try it yourself, although you'll have to look through the changes to guess how it works for now, and it might not work perfectly since I need to test it. When I have more time I'll elaborate further and finish this off.

**Comment by rbong** [comment]
I've now tested this with devicons and it should work. Here's how you customize this:

```vim
function! TabLabel(buf, max_width) abort
    let [l:left, l:name, l:short_name, l:right] = crystalline#default_tablabel_parts(a:buf, a:max_width)
    return l:left . l:short_name . ' ' . WebDevIconsGetFileTypeSymbol(l:name) . (l:right ==# ' ' ? '' : ' ') . l:right
endfunction

function! TabLine() abort
    return crystalline#bufferline(0, 0, 1, 1, 'TabLabel', crystalline#default_tabwidth() + 3)
endfunction
```

This will add a devicon to the right of the filename for each tab.

The first 4 arguments to the tabline are unrelated old arguments (items, width, show mode, enable mouse). The final 4 arguments are new. They are as follows:

   - tablabel: the name of the new function to use as the tab label. The function must take 2 arguments: the buffer number and the maximum width of the buffer name (not including indicators like modified indicator, filetype icon). The default left, name, shortened name, and right elements of the tab can be retrieved with the function `crystalline#default_tablabel_parts(buf, max_width)`.
   - tabwidth: the maximum width of all elements not including the buffer name. The default tab width can be retrieved with `crystalline#default_tabwidth()`. In this case, since we have a space before the devicon, the icon itself, and an optional space on the right, we add 3 to the default tab width.
   - tabitems: the maximum number of statusline items (special elements prefixed with a percent sign) per-tab. You usually will not need this on the tabline.
   - tabselitems: same as above, but for the currently selected tab.

I hope that is not too confusing. It is similar to adding more elements to the right of the tabline, except per-tab. Crystalline needs this information to build out the tabline without exceeding the maximum number of Vim elements and fit the maximum number of tabs on the screen with all of their indicators visible.

I'm leaving this open in case something went wrong, and also because I still need to document this. I need to find a way to more simply explain this before I can do that.

**Comment by kablondino** [comment]
I have been using a bit, tinkering around, and it seems great. Thanks for the quick implementation.

**Comment by luisdavim** [comment]
you should probably add these example to the readme

**Comment by rbong** [comment]
I think it's hard to show what the bufferline is doing just through example, however I've now added new bufferline features to the documentation.
