### ISSUE TITLE
question about themes

### ISSUE THREAD

**Issue by splitcircle** [rbong/vim-crystalline#7]
hey, love crystalline!

I'm trying to create a couple of themes with the end goal of making a PR, but I wanted to ask a clarifying question(and I apologize if it's painfully simple)

in this line: `\ 'NormalMode': [[189, 25], ['#d8dee9', '#0d61ac']],`, what are the first two values(in this case `[189, 25]`)? I can tell they relate to the hex values, just not sure how. 

Thanks!

**Comment by rbong** [comment]
Those are the terminal foreground and background colors.
Most terminals have only 256 colors and you can use an integer 0-255 to represent them.
So, the two first values should be the closest 256-color values to the following hex colors so that the theme is usable in the terminal.

The values in the object passed to `crystalline#generate_theme` should look like this:

```
[[ctermfg, ctermbg], [guifg, guibg], 'term=... cterm=... gui=...']
```

The last string with additional parameters is optional, and you don't need to include all of `term` `cterm` and `gui`.

These attributes (ctermfg, guifg, term, etc.) correspond to attributes that will be passed to the `:highlight` command.
See `:help highlight` for full information on using these attributes.

**Comment by splitcircle** [comment]
awesome, thank you
